name: Docker Build Check
on: 
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code 
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      
      - name: Install dependancies
        run:  pip install -r backend/requirements.txt

      - name: Run tests
        run: pytest
        working-directory: backend

      - name: Build Docker Image
        run: docker build -t milex-forecast ./backend